Boston house-prices dataset. The dataset consists of 13 features of 506 houses and the median home value in $1000's. You'll fit a model on the 13 features to predict the value of the houses.

https://archive.ics.uci.edu/ml/machine-learning-databases/housing/

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
import numpy as np

# Load the data from the boston house-prices dataset 
boston_data = load_boston()

In [2]:
data = np.loadtxt('housing.txt')
x = np.loadtxt('housing.txt')[:,:-1]
y = np.loadtxt('housing.txt')[:,-1:]

In [9]:
# These two lines below can load data directly from the web-link.

# x = boston_data['data']    # x-axis values; Rooms, School, Distance, and etc. 
# y = boston_data['target']   # Y-axis values; House price

In [10]:
x

(array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 array([[24. ],
        [21.6],
        [34.7],
        [33.4],
        [36.2],
        [28.7],
        [22.9],
        [27.1],
        [16.5],
        [18.9],
        [15. ],
        [18.9],
        [21.7],
        [20.4],
        [18.2],
        [19.9],
        [23.1],
        [17.5],
        [20.2],
        [18.2],
        [13.6],
        [19.6],
        [15.2],
        [14.5],
        [15.6],
        [

In [11]:
import pandas as pd
pd.DataFrame(data).head()  

# X axis => Number of Independent variables# [0 ~ 12] 
# Y axis => the target value.[13] 

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [6]:
# Make and fit the linear regression model
# TODO: Fit the model and assign it to the model variable

model = LinearRegression()  # Y = W1X1 + W2X2 + W3X3 + W4X5 + ... + Wn
model.fit(x, y)             # X0 ~ X12, 총 13개 독립변수에 대한 종속변수를 Fit

LinearRegression()

In [7]:
# Make a prediction using the model
'''
The new X-axis values. The number of values should match with the number of independent vars
'''
sample_house = [[2.29690000e-01, 0.00000000e+00, 1.05900000e+01, 0.00000000e+00, 4.89000000e-01,
                6.32600000e+00, 5.25000000e+01, 4.35490000e+00, 4.00000000e+00, 2.77000000e+02,
                1.86000000e+01, 3.94870000e+02, 1.09700000e+01]]

In [8]:
# TODO: Predict housing price for the sample_house
prediction = model.predict(sample_house)
prediction

array([[23.68284712]])

**The prediction is the predicted value based on the multiple regression model. This model can be useful when applying ratio analysis such as PER, PBR, EPS, PSR, and etc, in the stock price as the independent variables so to get the price estimation.**  