In [1]:
# TODO: Add import statements
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

train_data = pd.read_csv('data_polynomial.csv')
train_data.head()

Var_X    Var_Y
0 -0.33532  6.66854
1  0.02160  3.86398
2 -1.19438  5.16161
3 -0.65046  8.43823
4 -0.28001  5.57201

In [2]:
X = train_data['Var_X'].values
X

array([-0.33532,  0.0216 , -1.19438, -0.65046, -0.28001,  1.93258,
        1.2262 ,  0.74727,  3.32853,  2.87457, -1.48662,  0.37629,
        1.43918,  0.24183, -2.7914 ,  1.08176,  2.81555,  0.54924,
        2.36449, -1.01925])

In [3]:
X = train_data['Var_X'].values.reshape(-1, 1)
X

array([[-0.33532],
       [ 0.0216 ],
       [-1.19438],
       [-0.65046],
       [-0.28001],
       [ 1.93258],
       [ 1.2262 ],
       [ 0.74727],
       [ 3.32853],
       [ 2.87457],
       [-1.48662],
       [ 0.37629],
       [ 1.43918],
       [ 0.24183],
       [-2.7914 ],
       [ 1.08176],
       [ 2.81555],
       [ 0.54924],
       [ 2.36449],
       [-1.01925]])

In [13]:
pd.DataFrame(X)

0
0  -0.33532
1   0.02160
2  -1.19438
3  -0.65046
4  -0.28001
5   1.93258
6   1.22620
7   0.74727
8   3.32853
9   2.87457
10 -1.48662
11  0.37629
12  1.43918
13  0.24183
14 -2.79140
15  1.08176
16  2.81555
17  0.54924
18  2.36449
19 -1.01925

In [4]:
X.shape

(20, 1)

In [5]:
y = train_data['Var_Y'].values
y

array([  6.66854,   3.86398,   5.16161,   8.43823,   5.57201, -11.1327 ,
        -5.31226,  -4.63725,   3.8065 ,  -6.06084,   7.22328,   2.38887,
        -7.13415,   2.00412,   4.29794,  -5.86553,  -5.20711,  -3.52863,
       -10.16202,   5.31123])

In [14]:
pd.DataFrame(y)

0
0    6.66854
1    3.86398
2    5.16161
3    8.43823
4    5.57201
5  -11.13270
6   -5.31226
7   -4.63725
8    3.80650
9   -6.06084
10   7.22328
11   2.38887
12  -7.13415
13   2.00412
14   4.29794
15  -5.86553
16  -5.20711
17  -3.52863
18 -10.16202
19   5.31123

In [6]:
y.shape

(20,)

In [7]:
# Create polynomial features
# TODO: Create a PolynomialFeatures object, then fit and transform the
# predictor feature

poly_feat = PolynomialFeatures(degree = 4)   # Manually adjust the degree by looking at the plot result. 
poly_feat

PolynomialFeatures(degree=4)

In [16]:
X_poly = poly_feat.fit_transform(X)    # Degree 4 : 4 variables
X_poly

array([[ 1.00000000e+00, -3.35320000e-01,  1.12439502e-01,
        -3.77032139e-02,  1.26426417e-02],
       [ 1.00000000e+00,  2.16000000e-02,  4.66560000e-04,
         1.00776960e-05,  2.17678234e-07],
       [ 1.00000000e+00, -1.19438000e+00,  1.42654358e+00,
        -1.70383513e+00,  2.03502660e+00],
       [ 1.00000000e+00, -6.50460000e-01,  4.23098212e-01,
        -2.75208463e-01,  1.79012097e-01],
       [ 1.00000000e+00, -2.80010000e-01,  7.84056001e-02,
        -2.19543521e-02,  6.14743813e-03],
       [ 1.00000000e+00,  1.93258000e+00,  3.73486546e+00,
         7.21792628e+00,  1.39492200e+01],
       [ 1.00000000e+00,  1.22620000e+00,  1.50356644e+00,
         1.84367317e+00,  2.26071204e+00],
       [ 1.00000000e+00,  7.47270000e-01,  5.58412453e-01,
         4.17284874e-01,  3.11824468e-01],
       [ 1.00000000e+00,  3.32853000e+00,  1.10791120e+01,
         3.68771565e+01,  1.22746722e+02],
       [ 1.00000000e+00,  2.87457000e+00,  8.26315268e+00,
         2.37530108e+01

In [18]:
pd.DataFrame(X_poly)

0        1          2          3             4
0   1.0 -0.33532   0.112440  -0.037703  1.264264e-02
1   1.0  0.02160   0.000467   0.000010  2.176782e-07
2   1.0 -1.19438   1.426544  -1.703835  2.035027e+00
3   1.0 -0.65046   0.423098  -0.275208  1.790121e-01
4   1.0 -0.28001   0.078406  -0.021954  6.147438e-03
5   1.0  1.93258   3.734865   7.217926  1.394922e+01
6   1.0  1.22620   1.503566   1.843673  2.260712e+00
7   1.0  0.74727   0.558412   0.417285  3.118245e-01
8   1.0  3.32853  11.079112  36.877157  1.227467e+02
9   1.0  2.87457   8.263153  23.753011  6.827969e+01
10  1.0 -1.48662   2.210039  -3.285488  4.884272e+00
11  1.0  0.37629   0.141594   0.053280  2.004891e-02
12  1.0  1.43918   2.071239   2.980886  4.290031e+00
13  1.0  0.24183   0.058482   0.014143  3.420115e-03
14  1.0 -2.79140   7.791914 -21.750349  6.071392e+01
15  1.0  1.08176   1.170205   1.265881  1.369379e+00
16  1.0  2.81555   7.927322  22.319771  6.284243e+01
17  1.0  0.54924   0.301665   0.165686  9.100152e-02
18  1.0  2.36449   5.590813  13.219421  3.125719e+01
19  1.0 -1.01925   1.038871  -1.058869  1.079252e+00

In [9]:
# Make and fit the polynomial regression model
# TODO: Create a LinearRegression object and fit it to the polynomial predictor
# features

poly_model = LinearRegression(fit_intercept = False).fit(X_poly, y)

In [10]:
# TODO: Add import statements
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('data_polynomial.csv')
X = train_data['Var_X'].values.reshape(-1, 1)
y = train_data['Var_Y'].values

# Create polynomial features
# TODO: Create a PolynomialFeatures object, then fit and transform the
# predictor feature
poly_feat = PolynomialFeatures(degree = 4)
X_poly = poly_feat.fit_transform(X)

# Make and fit the polynomial regression model
# TODO: Create a LinearRegression object and fit it to the polynomial predictor
# features
poly_model = LinearRegression(fit_intercept = False).fit(X_poly, y)

In [11]:
poly_model

LinearRegression(fit_intercept=False)

In [12]:
prediction = poly_model.predict([[ 1.00000000e+00, -2.35320000e-01,  2.12439502e-01,
        -3.77032139e-02,  1.26426417e-02]])
prediction

array([4.33040859])