# Regularization

In [1]:
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression

In [2]:
df = np.loadtxt('data_regularization.txt', delimiter = ',')
df.shape

(100, 7)

In [3]:
df

array([[ 1.256640e+00,  2.049780e+00, -6.236400e+00,  4.719260e+00,
        -4.269310e+00,  2.059000e-01,  1.231798e+01],
       [-3.890120e+00, -3.751100e-01,  6.149790e+00,  4.945850e+00,
        -3.578440e+00,  6.400000e-03,  2.367628e+01],
       [ 5.097840e+00,  9.812000e-01, -2.993900e-01,  5.858050e+00,
         2.829700e-01, -2.062600e-01, -1.534590e+00],
       [ 3.903400e-01, -3.068610e+00, -5.634880e+00,  6.439410e+00,
         3.925600e-01, -7.084000e-02, -2.468670e+01],
       [ 5.847270e+00, -1.592200e-01,  1.141246e+01,  7.521650e+00,
         1.698860e+00,  2.902200e-01,  1.754122e+01],
       [-2.862020e+00, -8.433700e-01, -1.081650e+00,  6.711500e-01,
        -2.489110e+00,  5.232800e-01,  9.397890e+00],
       [-7.093280e+00, -7.233000e-02,  6.766320e+00,  1.306072e+01,
         1.287600e-01, -1.048000e-02,  1.173565e+01],
       [-7.176140e+00,  6.287500e-01, -2.899240e+00, -5.214580e+00,
        -2.703440e+00, -2.203500e-01,  4.424820e+00],
       [ 8.674300e+00,  

In [4]:
X = df[:,:-1]

In [5]:
y = df[:,-1:]

In [6]:
lasso_reg = Lasso()

In [7]:
lasso_reg.fit(X,y)

Lasso()

In [8]:
lasso_reg.coef_

array([ 0.        ,  2.35793224,  2.00441646, -0.05511954, -3.92808318,
        0.        ])

In [9]:
# TODO: Add import statements
import numpy as np
from sklearn.linear_model import Lasso

# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = np.loadtxt('data_regularization.txt', delimiter = ',')
X = train_data[:,:6]
y = train_data[:,-1:]

# TODO: Create the linear regression model with lasso regularization.
lasso_reg = Lasso()

# TODO: Fit the model.
lasso_reg.fit(X,y)

# TODO: Retrieve and print out the coefficients from the regression model.
reg_coef = lasso_reg.coef_
print(reg_coef)

[ 0.          2.35793224  2.00441646 -0.05511954 -3.92808318  0.        ]


Lasso regularization has set the `coefficients for the first and sixth columns to 0`. You might try fitting the model to a standard LinearRegression, to **see what those coefficients were before regularization!**

**vs LinearRegression Model**

In [10]:
lasso_reg = LinearRegression()
lasso_reg.fit(X,y)
reg_coef = lasso_reg.coef_
print(reg_coef)

[[-6.19918532e-03  2.96325160e+00  1.98199191e+00 -7.86249920e-02
  -3.95818772e+00  9.30786141e+00]]


# Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
X

array([[ 1.256640e+00,  2.049780e+00, -6.236400e+00,  4.719260e+00,
        -4.269310e+00,  2.059000e-01],
       [-3.890120e+00, -3.751100e-01,  6.149790e+00,  4.945850e+00,
        -3.578440e+00,  6.400000e-03],
       [ 5.097840e+00,  9.812000e-01, -2.993900e-01,  5.858050e+00,
         2.829700e-01, -2.062600e-01],
       [ 3.903400e-01, -3.068610e+00, -5.634880e+00,  6.439410e+00,
         3.925600e-01, -7.084000e-02],
       [ 5.847270e+00, -1.592200e-01,  1.141246e+01,  7.521650e+00,
         1.698860e+00,  2.902200e-01],
       [-2.862020e+00, -8.433700e-01, -1.081650e+00,  6.711500e-01,
        -2.489110e+00,  5.232800e-01],
       [-7.093280e+00, -7.233000e-02,  6.766320e+00,  1.306072e+01,
         1.287600e-01, -1.048000e-02],
       [-7.176140e+00,  6.287500e-01, -2.899240e+00, -5.214580e+00,
        -2.703440e+00, -2.203500e-01],
       [ 8.674300e+00,  2.099330e+00, -1.123591e+01, -5.995320e+00,
        -2.797700e+00, -8.710000e-02],
       [-6.033240e+00, -4.167240e+00,

In [14]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 2.40939098e-01,  1.29044717e+00, -1.32657695e+00,
         3.62755606e-01, -1.29448250e+00,  1.07584269e+00],
       [-6.89385644e-01, -1.12048023e-01,  1.17210015e+00,
         3.90650530e-01, -1.07641127e+00, -1.83941486e-02],
       [ 9.35271727e-01,  6.72407457e-01, -1.28898654e-01,
         5.02949170e-01,  1.42432265e-01, -1.18481222e+00],
       [ 8.43473152e-02, -1.66990046e+00, -1.20523179e+00,
         5.74518932e-01,  1.77024049e-01, -4.42047548e-01],
       [ 1.07073817e+00,  1.28173054e-02,  2.23374324e+00,
         7.07750768e-01,  5.89354080e-01,  1.53832915e+00],
       [-5.03547007e-01, -3.82877792e-01, -2.86704658e-01,
        -1.35597001e-01, -7.32567225e-01,  2.81663911e+00],
       [-1.26838661e+00,  6.30722889e-02,  1.29647329e+00,
         1.38965170e+00,  9.37562988e-02, -1.10979200e-01],
       [-1.28336432e+00,  4.68559271e-01, -6.53368701e-01,
        -8.60174370e-01, -8.00219905e-01, -1.26209441e+00],
       [ 1.58175014e+00,  1.31910564e+00, -2.335

In [15]:
lasso_reg = Lasso()

In [16]:
lasso_reg.fit(X_scaled, y)

Lasso()

In [17]:
reg_coef = lasso_reg.coef_
print(reg_coef)

[  0.           3.90753617   9.02575748  -0.         -11.78303187
   0.45340137]
